### ISSUE TITLE
Removal of anonymous types

### ISSUE THREAD

**Issue by mesemus** [techlib/CCMM#110]
CCMM, contains some anonymous complex types. In some cases, elements with the same "logical type", such as time instant, have different schemas according to where they are used. This brings unnecessary confusion when parsing the xsd file and when trying to understand it.

It would be nice to unify the types:

1) do not generate nested anonymous types, use top-level types only
2) for `TimeInstant` and `TimeInterval`, move the `date_type` from anonymous types to `time_reference` and then top-level types can be used without changes
3) for distribution file, create a top-level type
4) for distribution service there already is top-level type, but it is a type of `access_service` element, not of the distribution/service. Please rename the type of access_service element and create top-level type
5) for agent/organization, just use existing Organization top-level type as they contain the same fields
6) for agent/person, create a new top-level type
 
## List of schema files with anonymous types:
```
Checking: ccmm-xml-releases/ccmm-1.1.0-2025-10-25/out/time-reference.xsd
schema/complexType[type]/choice:
<xs:element xmlns:xs="http://www.w3.org/2001/XMLSchema" name="time_instant">
  <xs:complexType>
    <xs:sequence>
      <xs:choice>
        <xs:element name="date" type="date"/>
        <xs:element name="date_time" type="dateTime"/>
      </xs:choice>
      <xs:element minOccurs="0" name="date_information">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:attribute ref="xml:lang" use="required"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
      <xs:element name="date_type" type="date_type"/>
      <xs:element minOccurs="0" name="iri" type="anyURI"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

schema/complexType[type]/choice:
<xs:element xmlns:xs="http://www.w3.org/2001/XMLSchema" name="time_interval">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="beginning_time_instant" type="time_instant"/>
      <xs:element minOccurs="0" name="date_information">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:attribute ref="xml:lang" use="required"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
      <xs:element name="date_type" type="date_type"/>
      <xs:element name="end_time_instant" type="time_instant"/>
      <xs:element minOccurs="0" name="iri" type="anyURI"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

Checking: ccmm-xml-releases/ccmm-1.1.0-2025-10-25/out/distribution.xsd
schema/complexType[distribution]/choice:
<xs:element xmlns:xs="http://www.w3.org/2001/XMLSchema" name="distribution_data_service">
  <xs:complexType>
    <xs:sequence>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="access_service" type="data_service"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="description">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:attribute ref="xml:lang" use="required"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="documentation" type="documentation"/>
      <xs:element minOccurs="0" name="iri" type="anyURI"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="specification" type="application_profile"/>
      <xs:element name="title">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:attribute ref="xml:lang" use="required"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>

schema/complexType[distribution]/choice:
<xs:element xmlns:xs="http://www.w3.org/2001/XMLSchema" name="distribution_downloadable_file">
  <xs:complexType>
    <xs:sequence>
      <xs:element maxOccurs="unbounded" name="access_url" type="file"/>
      <xs:element name="byte_size" type="integer"/>
      <xs:element minOccurs="0" name="checksum" type="checksum"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="conforms_to_schema" type="application_profile"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="download_url" type="file"/>
      <xs:element name="format" type="format"/>
      <xs:element minOccurs="0" name="iri" type="anyURI"/>
      <xs:element minOccurs="0" name="media_type" type="media_type"/>
      <xs:element name="title">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:attribute ref="xml:lang" use="required"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>

Checking: ccmm-xml-releases/ccmm-1.1.0-2025-10-25/out/agent.xsd
schema/complexType[agent]/choice:
<xs:element xmlns:xs="http://www.w3.org/2001/XMLSchema" name="organization">
  <xs:complexType>
    <xs:sequence>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="alternate_name">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:attribute ref="xml:lang" use="required"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="contact_point" type="contact_details"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="identifier" type="identifier"/>
      <xs:element minOccurs="0" name="iri" type="anyURI"/>
      <xs:element name="name" type="string"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

schema/complexType[agent]/choice:
<xs:element xmlns:xs="http://www.w3.org/2001/XMLSchema" name="person">
  <xs:complexType>
    <xs:sequence>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="affiliation" type="organization"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="contact_point" type="contact_details"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="family_name" type="string"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="given_name" type="string"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="identifier" type="identifier"/>
      <xs:element minOccurs="0" name="iri" type="anyURI"/>
      <xs:element name="name" type="string"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>
```

**Comment by MichalMed** [comment]
Same as #107 , this shall be partly solved by #42 at least for agent and time reference. 
That leaves us just with distribution. Anyway, please @mesemus check it in the current 1.1.0 commit.

**Comment by mesemus** [comment]
At least with time_reference the latest commit does not solve the issue. The nested types have been removed but a new issue with data_type has been introduced - time_reference does not have it, time_instant does not have it (imho correctly), time_interval has it (imho incorrectly)

**Comment by mesemus** [comment]
"Agent" still contains a nested "Person", so this part is not solved as well.
